### ISSUE TITLE
Grammar doesn't accept when an equation begins with +, - , 

### ISSUE THREAD

**Issue by srija-ieee** [hindawiai/hindawi2020#1]
In hincc yacc program, thhe grammar defined dosen't accept equations beginning with +, -,

**Comment by obonac** [comment]
Bug accepted
Equations beginning with '+' are not accepted

Please check the error reported for equations beginning with '-'

**Comment by obonac** [comment]
Resolved via https://github.com/hindawiai/hindawi2020/tree/obonac-patch-1

**Comment by obonac** [comment]
@srija-ieee kindly check with latest master

**Comment by srija-ieee** [comment]
Verified - Fixed
